// github-api.js — Pure GitHub REST API wrapper (no cloning required)

const API = "https://api.github.com";
const REPO_NAME = "ghost-commits-repo";

/**
 * Standard headers for every GitHub API call.
 */
function headers(token) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "Content-Type": "application/json",
  };
}

/**
 * Small fetch wrapper that throws on non-2xx.
 */
async function ghFetch(token, method, path, body = null) {
  const opts = { method, headers: headers(token) };
  if (body) opts.body = JSON.stringify(body);
  const res = await fetch(`${API}${path}`, opts);
  const data = await res.json().catch(() => null);
  if (!res.ok) {
    const msg = data?.message || res.statusText;
    const err = new Error(`GitHub ${method} ${path}: ${res.status} ${msg}`);
    err.status = res.status;
    err.data = data;
    throw err;
  }
  return data;
}

// ─── Public API ──────────────────────────────────────────────

/**
 * GET /user — returns { login, email, name, ... }
 */
export async function getAuthenticatedUser(token) {
  return ghFetch(token, "GET", "/user");
}

/**
 * Fetch the user's verified, primary email.
 * Falls back to /user .email if /user/emails is forbidden (classic PAT w/o user:email scope).
 */
export async function getUserEmail(token) {
  try {
    const emails = await ghFetch(token, "GET", "/user/emails");
    const primary = emails.find((e) => e.primary && e.verified);
    if (primary) return primary.email;
    const verified = emails.find((e) => e.verified);
    if (verified) return verified.email;
  } catch {
    // Fine-grained PATs may not have email scope — fall back.
  }
  const user = await getAuthenticatedUser(token);
  return user.email; // may be null if private
}

/**
 * Create the private ghost-commits repo (idempotent).
 * Returns { owner, repo, html_url }.
 */
export async function createPrivateRepo(token) {
  try {
    const data = await ghFetch(token, "POST", "/user/repos", {
      name: REPO_NAME,
      private: true,
      auto_init: true, // creates initial commit so Git Data API works
      description:
        "🟩 Auto-generated by Ghost Commits — keeps your contribution graph green.",
    });
    return { owner: data.owner.login, repo: data.name, html_url: data.html_url };
  } catch (err) {
    if (err.status === 422) {
      // Repo already exists — fetch it instead.
      const user = await getAuthenticatedUser(token);
      const data = await ghFetch(
        token,
        "GET",
        `/repos/${user.login}/${REPO_NAME}`
      );
      return { owner: data.owner.login, repo: data.name, html_url: data.html_url };
    }
    throw err;
  }
}

/**
 * Get the SHA of the latest commit on the default branch (main).
 */
export async function getLatestCommitSha(token, owner, repo, branch = "main") {
  const data = await ghFetch(
    token,
    "GET",
    `/repos/${owner}/${repo}/git/ref/heads/${branch}`
  );
  return data.object.sha;
}

/**
 * Create a single ghost commit via the Git Data API.
 *
 * Flow: create blob → create tree → create commit → update ref
 *
 * Each commit appends a timestamped line to `ghost.txt` so there is a real diff.
 */
export async function createGhostCommit(
  token,
  owner,
  repo,
  email,
  authorName,
  commitDate = null
) {
  const branch = "main";
  const now = commitDate ? new Date(commitDate) : new Date();
  const isoDate = now.toISOString();

  // 1. Get current commit + its tree
  const parentSha = await getLatestCommitSha(token, owner, repo, branch);
  const parentCommit = await ghFetch(
    token,
    "GET",
    `/repos/${owner}/${repo}/git/commits/${parentSha}`
  );
  const baseTreeSha = parentCommit.tree.sha;

  // 2. Create a blob (the file content)
  const content = `ghost commit @ ${isoDate}\n`;
  const blob = await ghFetch(
    token,
    "POST",
    `/repos/${owner}/${repo}/git/blobs`,
    { content, encoding: "utf-8" }
  );

  // 3. Create a tree that adds/appends to ghost.txt
  const tree = await ghFetch(
    token,
    "POST",
    `/repos/${owner}/${repo}/git/trees`,
    {
      base_tree: baseTreeSha,
      tree: [
        {
          path: "ghost.txt",
          mode: "100644",
          type: "blob",
          sha: blob.sha,
        },
      ],
    }
  );

  // 4. Create the commit
  const commit = await ghFetch(
    token,
    "POST",
    `/repos/${owner}/${repo}/git/commits`,
    {
      message: `👻 ghost commit — ${isoDate}`,
      tree: tree.sha,
      parents: [parentSha],
      author: {
        name: authorName || "Ghost Commits",
        email: email,
        date: isoDate,
      },
    }
  );

  // 5. Fast-forward the branch ref
  await ghFetch(
    token,
    "PATCH",
    `/repos/${owner}/${repo}/git/refs/heads/${branch}`,
    { sha: commit.sha }
  );

  return { sha: commit.sha, date: isoDate };
}
